services:
  caddy:
    image: caddy:alpine
    container_name: stock_daily
    restart: unless-stopped
    ports:
      - "9005:80"
    volumes:
      - ./index:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
